version: '3'
services:
  flask-api:
    build:
      context: link/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  ui:
    build:
      context: ui/
      dockerfile: Dockerfile
    ports:
      - "1111:80"
